theme: jekyll-theme-dinky
title: Lehyu's Blog
email: 951908719@qq.com
description: > # this means to ignore newlines until "baseurl:"
   What you lost today would be what you want tomorrow. Treasure the present and live in the moment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.Lehyu.cn" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  Lehyu

# Build settings
encoding: UTF-8

markdown: kramdown
markdown_ext: md
